name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Generate DSL
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: :dsl-generator:run
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'dsl/src/main/kotlin'
          message: 'Update DSL'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
      - name: Test
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: :example:run
      - name: Is New Release
        id: isNewRelease
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: isNewRelease
        env:
          GITHUB_USER: github-action
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - name: Setup git user
        if: steps.isNewRelease.outcome == 'success'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Publish
        uses: burrunan/gradle-cache-action@v1
        if: steps.isNewRelease.outcome == 'success'
        with:
          arguments: :publish
        env:
          GITHUB_USER: github-action
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}