name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Test
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: :example:run
      - name: Is New Release
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: isNewRelease
        continue-on-error: true
      - name: Publish
        uses: burrunan/gradle-cache-action@v1
        if: steps.isNewRelease.outcome == 'success'
        with:
          arguments: :publish
        env:
          GITHUB_USER: github-action
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}