name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4.8.0
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.ref }}
      - name: Generate DSL
        uses: burrunan/gradle-cache-action@v3.0.2
        with:
          arguments: :dsl-generator:run
      - name: Test
        uses: burrunan/gradle-cache-action@v3.0.2
        with:
          arguments: :example:run