name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ github.ref }}
      - name: Generate DSL
        uses: burrunan/gradle-cache-action@v3
        with:
          arguments: :dsl-generator:run
      - name: Test
        uses: burrunan/gradle-cache-action@v3
        with:
          arguments: :example:run